### PR TITLE
Prevent output of featured image in player, staff, and team profiles.

### PR DESCRIPTION
**Pull request by brianmiyaji**
A few of the SportsPress templates (players, staff, and teams) output their own inline featured images, so this pull will prevent doubling up with the standard featured image :)

Related: https://wordpress.org/support/topic/duplicate-image-4/#post-8149376

### CODE REVIEW

**Comment by samikeijonen** [comment]
Thanks!

I was wondering should we do this using conditional checks like `is_singular( 'player' )`?

**Comment by samikeijonen** [comment]
Meaning something like this in `content.php`.

```
! is_singular( 'player' ) :
   chuchadon_post_thumbnail();
endif;
```

**Comment by brianmiyaji** [comment]
Yep a conditional would work too. Actually, since there's already a chuchadon_post_thumbnail() function, how's this? fa4db9d

**Comment by samikeijonen** [comment]
Sorry I missed your new PR. This is much better approach when conditional logic is in template function. I'll test it out and submit new theme version in .org.

**Review by samikeijonen — APPROVED** [review]
Looks good.

**Pull request merged**
